site_name: Ifeanyi Asonye.
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: teal


  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tab.sticky
    - navigation.footer
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.code.copy


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
generator: false

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md 

plugins:
- search
- blog



copyright: Copyright &copy; 2026 Ifeanyi Asonye. All rights reserved.
