site_name: Ifeanyi.  
site_url: https://mydomain.org/mysite
theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.expand
    - toc.integrate
    - toc.follow
    - content.code.copy
    - content.tabs.link



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
  generator: false

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md

  - Blog:
    - blog/index.md

plugins:
- search
- blog:
    blog_dir: .

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true